# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks


repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # - id: check-added-large-files
      #   stages: [commit]
      - id: check-ast
        stages: [commit]
      - id: check-case-conflict
        stages: [commit]
      - id: check-docstring-first
        stages: [commit]
      - id: check-merge-conflict
        stages: [commit]
      - id: check-symlinks
        stages: [commit]
      - id: check-xml
        stages: [commit]
      - id: check-yaml
        stages: [commit]
      - id: debug-statements
        stages: [commit]
      - id: end-of-file-fixer
        stages: [commit]
      - id: mixed-line-ending
        stages: [commit]
      - id: trailing-whitespace
        stages: [commit]
      - id: fix-byte-order-marker
        stages: [commit]

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        stages: [commit]
        args: [".", "--line-length=101"]
  # - repo: https://github.com/PyCQA/isort
  #   rev: 5.11.4
  #   hooks:
  #     - id: isort
  #       stages: [commit]
  #       args: ["--profile", "black"]
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
      - id: shell-lint
        args: [--format=json, --exclude=SC1091]
