# Database configuration for TradingViewAlgoDev
# Set the path to the SQLite database file. If not set, defaults to open_trading_algo/tv_data_cache.sqlite3


db_path: data/tv_data_cache.sqlite3
enable_caching: true
